# Example Loki config for local or test deployments
# See https://grafana.com/docs/loki/latest/configuration/

server:
  http_listen_port: 3100

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    ring:
      kvstore:
        store: inmemory


schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  retention_period: ${LOKI_RETENTION_PERIOD}
  max_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 168h

# Optional: Enable authentication if required
# auth_enabled: ${LOKI_AUTH_ENABLED}
